version: '3.9'

services:
  # Spring Boot App
  contacts-api:
    container_name: contacts-api-java
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      DB_USER: postgres
      DB_PASS: 12345
      DB_HOST: contacts-api-db
      DB_PORT: 5432
      DB_NAME: contacts-api
    ports:
      - "8080:8080"
    depends_on:
      - contacts-api-db
    networks:
      - contacts-api

  # Database
  contacts-api-db:
    container_name: contacts-api-db-postgres
    image: postgres
    restart: unless-stopped
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: contacts-api
    networks:
      - contacts-api

  # Management Database
  contacts-api-pgadmin:
    container_name: contacts-api-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - contacts-api-db
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'contacts-api@domain.com'
      PGADMIN_DEFAULT_PASSWORD: 12345
    networks:
      - contacts-api

networks:
  # Contacts API Network
  contacts-api:
    name: contacts-api-network
