@startuml "Contacts API - Context Diagram C4Model"
!include styles.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN()
HIDE_STEREOTYPE()


' Tags support no spaces in the name (based on the underlining stereotypes, which don't support spaces anymore).
AddElementTag("softwareSystem", $fontColor=$ELEMENT_FONT_COLOR, $bgColor="#1168bd", $legendText="software system")
AddRelTag("async", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DashedLine())

title Diagrama de Contexto MS-Contactos

SHOW_PERSON_OUTLINE()

Person(customer, Usuario Final, "El usuario que usa la aplicación de contactos", $sprite="person", $type="Person")
System(contacts_system, "MS-Contactos\n<size:10>[Software System]</size>", "Permite la gestión de una lista de contactos", $tags="softwareSystem")
System_Ext(mail, "E-mail System", "Software interno de intercambio de correos electrónicos.")

Rel(customer, contacts_system, "Crea, edita o elimina contactos.")
Rel_Back(customer, mail, "Envía e-mails a", $tags="async")
Rel_Neighbor(contacts_system, mail, "Envía e-mails", "SMTP", $tags="async")

SHOW_FLOATING_LEGEND()

caption \nFigure 1: [Contexto del Sistema] MS-Contactos
footer diagrama creado con PlantUML v. %version() y C4-PlantUML v. C4Version()
@enduml
