@startuml
left to right direction

skinparam packageStyle rectangle

package "Contacts" {
    usecase "List Contacts" as US1
    usecase "View Contact" as US2
    usecase "Create Contact" as US3
    usecase "Update Contact" as US4
    usecase "Delete Contact" as US5
}

actor :User: as User

User --> (US1)
User --> (US2)
User --> (US3)
User --> (US4)
User --> (US5)
@enduml
